### PR TITLE
#3137444 - Export manager tests/feature - Config.

### PR DESCRIPTION
**Pull request by shabananavas**
https://www.drupal.org/project/entity_sync/issues/3137444

### CODE REVIEW

**Comment by krystalcode** [comment]
@shabananavas  can you be adding a link to the Drupal.org issue in the description of all PRs?

**Comment by shabananavas** [comment]
> @shabananavas can you be adding a link to the Drupal.org issue in the description of all PRs?

Done.

**Comment by shabananavas** [comment]
@barnettech I've started the base for the export manager tests based on MR #22 pushed by Dimitris. This adds the initial test to test the configuration and the feature in the appropriate export Manager class.

We basically, now have to continue building on this and add tests that test the rest of the functionality and write the required functionality for it in the Manager class.

**Comment by shabananavas** [comment]
Closing in favor of #30

**Pull request closed without merging**
